let experienceList = [
  {
    id: 1,
    title: "Frontend Web Developer",
    company: "Tailored Brands",
    location: "Fremont, CA",
    tags: [
      "react.js",
      "node.js",
      "javascript",
      "html5",
      "css3",
      "jquery",
      "gulp",
      "pug",
      "sass",
      "github",
      "gcp",
      "jira",
      "websphere",
    ],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "August 2021 - present",
    icon: "work",
  },
  {
    id: 2,
    title: "Jr. Software Engineer",
    company: "DomaniSystems Inc.",
    location: "Shelton, CT",
    tags: [
      "react.js",
      "node.js",
      "javascript",
      "html5",
      "css3",
      "jquery",
      "qt",
      "github",
      "firebase",
      "gcp",
    ],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "July 2020 - August 2021",
    icon: "work",
  },
  {
    id: 3,
    title: "Software Developer Intern",
    company: "DomaniSystems Inc.",
    location: "Shelton, CT",
    tags: [
      "react.js",
      "node.js",
      "javascript",
      "html5",
      "css3",
      "jquery",
      "qt",
      "github",
      "firebase",
      "gcp",
    ],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "September 2019 - May 2020",
    icon: "work",
  },
  {
    id: 4,
    title: "Web Developer (Student Worker)",
    company: "University of Bridgeport",
    location: "Bridgeport, CT",
    tags: [
      "wordpress",
      "drupal",
      "mysql",
      "php",
      "microsoft-dynamics-365-crm",
      "google-analytics",
      "redux",
      "API",
      "firebase",
      "material-ui",
    ],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "September 2018 - September 2019",
    icon: "work",
  },
  {
    id: 5,
    title: "Teaching Assistant",
    company: "Google CSSI, University of Bridgeport",
    location: "Bridgeport, CT",
    tags: ["react.js", "node.js", "redux", "API", "firebase", "material-ui"],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "July 2019 - August 2019",
    icon: "work",
  },
  {
    id: 6,
    title: "Web Developer",
    company: "Dheya Career Mentors (I) Pvt Ltd",
    location: "Pune, India",
    tags: ["react.js", "node.js", "redux", "API", "firebase", "material-ui"],
    // description:
    //   "Converting data to a graphical interface, through the use of HTML, CSS, and JavaScript, so that users can view and interact with that data.",
    buttonText: "View Frontend Projects",
    date: "June 2014 - July 2018",
    icon: "work",
  },
];

export default experienceList;
